### ISSUE TITLE
Using with Touch Portal

### ISSUE THREAD

**Issue by clothlust** [GlitchedMythos/se-widgets#49]
Hi there, 

how do i merge this with a touch portal (steam deck alternative)? Do i have to individually input the commend & is it possible for the commends not to appear in chat. 

Many thanks!!

PS. love your widget

**Comment by billyjbryant** [comment]
You have to individually input the commands on to each touchportal button. The only mechanism for the commands to not appear into chat would be to set up stream elements under a different Twitch Account and create the widget there. Then have TouchPortal linked to that account as well so that commands are sent to the non-active account's chat.

**Comment by GlitchedMythos** [comment]
I reached out a little while ago because there was talk of a StreamElements API that could be hit. Looks like that won't happen, and will probably be out of scope if it did happen.
